# Generated by Django 3.2 on 2021-05-11 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=50, verbose_name='difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=5, verbose_name='pixels')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default=True, max_length=50, unique=True, verbose_name='topic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=50)),
                ('content', models.TextField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('difficulty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='playroom.difficulty')),
                ('pixels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='playroom.pixel')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='playroom.topic')),
            ],
            options={
                'ordering': ['topic', 'difficulty'],
            },
        ),
        migrations.AddField(
            model_name='difficulty',
            name='pixels',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='playroom.pixel'),
        ),
    ]
