# Generated by Django 3.2 on 2021-06-02 10:29

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('yummypython', '0003_alter_subtopic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='content',
            field=martor.models.MartorField(default=True),
        ),
    ]
